{ stdenv }:

stdenv.mkDerivation rec {
  pname = "user-modules";
  version = "23.05";

  phases = [ "installPhase" ];

  installPhase = ''
    mkdir -p $out/modules/${pname}

    cat > $out/modules/${pname}/${version}.lua << EOF
    -- ${pname}/${version}.lua
    -- autogenerated by lmix

    local pkgName = myModuleName()
    local version = myModuleVersion()

    prepend_path("MODULEPATH", "~/.nix-profile/modules")
    EOF
  '';
}