{ stdenv }:

stdenv.mkDerivation rec {
  pname = "user-modules";
  version = import ../pkgs-ver.nix;

  phases = [ "installPhase" ];

  installPhase = ''
    mkdir -p $out/${version}/${pname}

    cat > $out/${version}/${pname}/${version}.lua << EOF
    -- ${pname}/${version}.lua
    -- autogenerated by lmix

    local pkgName = myModuleName()
    local version = myModuleVersion()

    prepend_path("MODULEPATH", "~/.nix-profile/${version}")
    EOF
  '';
}